version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "./"
      - "./magefiles"
    schedule:
      interval: "weekly"
    groups:
      gomod:
        patterns:
          - "*"
