version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - mage
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: traefik-acme
    main: ./cmd/traefik-acme
    binary: traefik-acme
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    ldflags:
      - "-X github.com/dosquad/go-cliversion.BuildDate={{ .Date }}"
      - "-X github.com/dosquad/go-cliversion.BuildDebug=false"
      - "-X github.com/dosquad/go-cliversion.BuildMethod=goreleaser"
      - "-X github.com/dosquad/go-cliversion.BuildVersion={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitCommit={{.ShortCommit}}"
      - '-X github.com/dosquad/go-cliversion.GitRepo={{.GitURL}}'
      - '-X github.com/dosquad/go-cliversion.GitSlug={{- $gitsa := split (trimsuffix .GitURL ".git") ":" -}}{{- $gitsp := split (index $gitsa 1) "/" -}}{{- $size := len $gitsp -}}{{- $sla := len (slice (printf "%*s" $size "") 2) -}}{{ $slb := len (slice (printf "%*s" $size "") 1) -}}{{index $gitsp $sla}}/{{index $gitsp $slb}}'
      - "-X github.com/dosquad/go-cliversion.GitTag={{.Version}}"
      - "-X github.com/dosquad/go-cliversion.GitExactTag={{.RawVersion}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{ .Date }}"
      - "-X main.builtBy=goreleaser"
      - "-X main.repo={{.GitURL}}"
      - "-X main.goVersion=1.22.4"
      - "-X main.version={{.Version}}"
      - "-s"
      - "-w"
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: traefik-acme-nfpms
    package_name: traefik-acme
    builds:
      - traefik-acme
    homepage: https://github.com/na4ma4/traefik-acme
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: Traefik ACME extraction tool.
    formats:
      - apk
      - deb
    bindir: /usr/bin
