env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: traefik-acme
    main: ./cmd/traefik-acme
    binary: traefik-acme
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [ '5', '6', '7' ]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    id: traefik-acme-nfpms
    package_name: traefik-acme
    builds:
      - traefik-acme
    homepage: https://github.com/na4ma4/traefik-acme
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: Traefik ACME extraction tool.
    formats:
      - apk
      - deb
    bindir: /usr/bin
